# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fhWu__gIMd1V0FVSNn9IykhkQUz22vpT
"""

pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

time= ctrl.Antecedent(np.arange(10,181,1),'time')
rice= ctrl.Antecedent(np.arange(100,2001,1),'rice')
power= ctrl.Consequent(np.arange(0,101,1),'power')

time['vf']=fuzz.trimf(time.universe,[10,10,30])
time['f']=fuzz.trimf(time.universe,[20,40,60])
time['n']=fuzz.trimf(time.universe,[40,80,115])
time['s']=fuzz.trimf(time.universe,[100,125,150])
time['vs']=fuzz.trimf(time.universe,[130,180,180])

rice['vm']=fuzz.trimf(rice.universe,[100,100,550])
rice['m']=fuzz.trimf(rice.universe,[450,700,950])
rice['n']=fuzz.trimf(rice.universe,[850,1100,1350])
rice['l']=fuzz.trimf(rice.universe,[1250,1450,1650])
rice['vl']=fuzz.trimf(rice.universe,[1550,2000,2000])

power['vless']=fuzz.trimf(power.universe,[0,20,35])
power['less']=fuzz.trimf(power.universe,[25,40,55])
power['nomal']=fuzz.trimf(power.universe,[45,60,75])
power['much']=fuzz.trimf(power.universe,[65,80,95])
power['vmuch']=fuzz.trimf(power.universe,[85,100,100])

rule1= ctrl.Rule(time['vf']&rice['vm'],power['nomal'])
rule2= ctrl.Rule(time['vf']&rice['m'],power['much'])
rule3= ctrl.Rule(time['vf']&rice['n'],power['much'])
rule4= ctrl.Rule(time['vf']&rice['l'],power['much'])
rule5= ctrl.Rule(time['vf']&rice['vl'],power['vmuch'])

rule6= ctrl.Rule(time['f']&rice['vm'],power['nomal'])
rule7= ctrl.Rule(time['f']&rice['m'],power['nomal'])
rule8= ctrl.Rule(time['f']&rice['n'],power['nomal'])
rule9= ctrl.Rule(time['f']&rice['l'],power['much'])
rule10= ctrl.Rule(time['f']&rice['vl'],power['much'])

rule11= ctrl.Rule(time['n']&rice['vm'],power['less'])
rule12= ctrl.Rule(time['n']&rice['m'],power['less'])
rule13= ctrl.Rule(time['n']&rice['n'],power['nomal'])
rule14= ctrl.Rule(time['n']&rice['l'],power['nomal'])
rule15= ctrl.Rule(time['n']&rice['vl'],power['nomal'])

rule16= ctrl.Rule(time['s']&rice['vm'],power['vless'])
rule17= ctrl.Rule(time['s']&rice['m'],power['vless'])
rule18= ctrl.Rule(time['s']&rice['n'],power['vless'])
rule19= ctrl.Rule(time['s']&rice['l'],power['less'])
rule20= ctrl.Rule(time['s']&rice['vl'],power['less'])

rule21= ctrl.Rule(time['vs']&rice['vm'],power['vless'])
rule22= ctrl.Rule(time['vs']&rice['m'],power['vless'])
rule23= ctrl.Rule(time['vs']&rice['n'],power['vless'])
rule24= ctrl.Rule(time['vs']&rice['l'],power['vless'])
rule25= ctrl.Rule(time['vs']&rice['vl'],power['less'])
 
powerout_ctrl= ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5,
                                  rule6,rule7,rule8,rule9,rule10,
                                  rule11,rule12,rule13,rule14,rule15,
                                  rule16,rule17,rule18,rule19,rule20,
                                  rule21,rule22,rule23,rule24,rule25,])
powerout= ctrl.ControlSystemSimulation(powerout_ctrl)

powerout.input['time']=30
powerout.input['rice']=1548
powerout.compute()
print(powerout.output['power'])
power.view(sim=powerout)

